# define version of docker compose config version
version: '3'

# define services
services:
  # define service with flask app
  flask-app:
    # use Dockerfile from `flask-app-src` directory
    build:
      ./flask-app-src
    # bind container ports to host ports (container:host)
    ports:
      - "8080:5000"
    volumes:
      - ./flask-app-src:/code/

  # define service with redis server
  redis:
    image: "redis:latest"

  # define service with nginx for serving static
  # and reverse proxy to server apps
  reverseproxy:
    build:
      ./nginx-reverseproxy
    ports:
      - "8081:80"
    volumes:
      - ./nginx-reverseproxy/config:/etc/nginx/conf.d/
      - ./fe-app/dist:/static/dist/
    restart: always
